### ISSUE TITLE
[Feature] Wallet Connect

### ISSUE THREAD

**Issue by D4v3sb** [vipago/mpago#7]
O [Wallet Connect](https://www.mercadopago.com.br/developers/pt/docs/wallet-connect/landing) permite salvar as informações do comprador para futuros pagamentos utilizando sua conta do Mercado Pago, após a aprovação.

O fluxo é dividido em 3:

## [Criação do Agreement](https://www.mercadopago.com.br/developers/pt/docs/wallet-connect/account-linking-flow/create-agreement)
Cria o link pro comprador acessar e permitir que o vendedor acesse sua carteira do mercado pago para a realização do pagamento.

[**Documentação API**](https://www.mercadopago.com.br/developers/pt/reference/wallet_connect/_wallet_connect_agreements/post)

<details open>
<summary>Imagem do Fluxo</summary>
<img width="1085" alt="Fluxo Criação do Agreement" src="https://github.com/vipago/mpago/assets/86922268/c8aaf1d1-5cf3-4f73-8690-35607a8201ce">
</details>

## [Obtenção da Aprovação](https://www.mercadopago.com.br/developers/pt/docs/wallet-connect/account-linking-flow/get-approval)

Agora o comprador aprova a utilização dos dados de pagamento dele.

Irá receber um `GET` no `return_uri` setado na criação do agreement com a query string `agreement_code`

<details open>
<summary>Imagem do Fluxo</summary>
<img width="1085" alt="Fluxo Obtenção da Aprovação" src="https://github.com/vipago/mpago/assets/86922268/9fd1a5cb-0e1c-4a8a-95a3-51994b36bcb2">
</details>

## [Criação do Payer Token](https://www.mercadopago.com.br/developers/pt/docs/wallet-connect/account-linking-flow/create-payer-token)

Esse o que armazena os dados do comprador, ele é válido pelo durante um período ou até ser revogado. A gente vai utilizar ele pra criar os pagamentos

[**Documentação API**](https://www.mercadopago.com.br/developers/pt/reference/wallet_connect/_wallet_connect_agreements_agreement_id_payer_token/post)

<details open>
<summary>Imagem do Fluxo</summary>
<img alt="Fluxo Criação do Payer Token" src="https://github.com/vipago/mpago/assets/86922268/8f1b54c8-41d1-4909-b85a-cd9d3fbe6f09">
</details>

**Comment by coffee-is-power** [comment]
@D4v3sb É que eu ainda não entendi a diferença de fazer isso para a pessoa logar com oauth2, guardar o refresh token e a gente criar pagamentos usando o refresh token.

**Comment by D4v3sb** [comment]
> @D4v3sb É que eu ainda não entendi a diferença de fazer isso para a pessoa logar com oauth2, guardar o refresh token e a gente criar pagamentos usando o refresh token.

O OAuth2 é um fluxo **integrador-vendedor**. Ele vai permitir que crie pagamentos na conta do vendedor, ou seja, ele recebe o dinheiro.

O Wallet Connect é um fluxo **vendedor-comprador**. Ele cria um token de permissão do comprador para que o vendedor faça cobranças, com o comprador podendo escolher se quer pagar com o saldo da conta ou algum cartão.

Então primeiro é criada a integração com a conta do vendedor, retornando um `access_token`, que será usado pra criar o pagamento. Depois pode ser usado o Wallet Connect, que vai ser a permissão do comprador para o vendedor poder debitar, e retorna o `payer_token`.

Na criação do pagamento, é passado o `access_token` e o `payer_token`, onde vai fazer a cobrança e o débito automático da conta do comprador.

**Comment by coffee-is-power** [comment]
Faz sentido, então o que eu tenho na vipago tá errado então, porque o oauth2 so aceita conta de vendedor e eu tava tentando criar um pagamento em conta de vendedor, ent la vamos nós voltar pra trás dnv yay :fireworks: :fireworks:

**Comment by coffee-is-power** [comment]
@D4v3sb Já ta desenvolvendo isso daq? eu realmente preciso pra integrar na vipago.

**Comment by coffee-is-power** [comment]
Acho que já vou começar a implementar isso aqui hoje pra nao perdermos mais tempo

**Comment by D4v3sb** [comment]
> Acho que já vou começar a implementar isso aqui hoje pra nao perdermos mais tempo

Pode fazer então e depois eu reviso. Não vou ter tempo hoje pra mexer

**Comment by coffee-is-power** [comment]
Acabei de subir o draft no Pull request #8

**Comment by D4v3sb** [comment]
![image](https://github.com/vipago/mpago/assets/86922268/37f57ba2-c5ec-460e-badf-2bf403b977bf)
